version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "qwerty123"
      POSTGRES_DB: AiBot
    ports:
      - "5432:5432"

volumes:
  postgres_data:
